# -*- coding: utf-8 -*-
"""predict using supervised ML

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BUY8mPFN8swtQHiM8dQ2JA-35JBcMa-l
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Load the data from the CSV file
data = pd.read_csv('studentscore.csv')

# Extract the features (number of hours) and the target variable (scores)
X = data['Hours'].values.reshape(-1, 1)
y = data['Scores'].values

# Create and fit the linear regression model
model = LinearRegression()
model.fit(X, y)

# Predict the scores for new data
hours = [[9.5]]  # Provide the number of hours for prediction
predicted_scores = model.predict(hours)

print(f"Predicted score for {hours[0][0]} hours of study: {predicted_scores[0]}")